version: "3"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: github_explorer
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data_volume:/var/lib/mysql

  app:
    build: .
    command: bash -c "rm -rf /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: github_explorer
      DB_HOST: db

#Docker Networks
volumes:
  data_volume:
